version: '2.2'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: localdev
      POSTGRES_DB: pastie
      POSTGRES_USER: pastie

